@baseUrl = http://localhost:3000

### @name createRoom <-- Você pode mudar o nome para algo como createReminder
# @name createReminder
POST {{baseUrl}}/api/reminders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21lIjoibWF0aGV1cyIsImVtYWlsIjoibWF0aGV1cy5jYW1wb3NAZ21haWwuY29tIiwiaWF0IjoxNzU5OTUwMDgyLCJleHAiOjE3NjAwMzY0ODIsInN1YiI6ImNtZzFhemdwcTAwMDBpY2hiOXF5NmVyeHIifQ.ojfXLDkx_wSv3MQDfz28enYQTP8dSMdVJ-PW01Ljpu4


{
  "message": "Pagar jessica",
  "notificationDate": "2025-10-08T16:51:00"

}

###
# @name listReminders
GET {{baseUrl}}/api/reminders



###
# @name listRemindersById
GET  {{baseUrl}}/api/reminders/cmfx1ju3s0000icdcek3nk4jd



###
# @name deleteReminder
DELETE {{baseUrl}}/api/reminders/cmfx0y6b60000icufqoshe5co


###
# @name patchReminder
PATCH  {{baseUrl}}/api/reminders/cmfx11bq60001icufytsel1uq
Content-Type: application/json


{
  "message": "Teste",
  "notificationDate": "2023-04-30T13:00:00"

}



###
# @name userCreate
POST {{baseUrl}}/api/users
Content-Type: application/json


{
  "name": "ma",
  "email": "matheus.campos@",
  "password": "123"

}


###
# @name sessionsCreate

POST {{baseUrl}}/api/sessions
Content-Type: application/json


{
  "name": "matheus",
  "email": "matheus.campos@gmail.com",
  "password": "123"

}